spring:
  couchbase:
    bootstrap-hosts: 192.168.99.100
    bucket:
      name: music_host
      password: password
    env:
      timeouts:
        connect: 30000ms
        socket-connect: 10000ms
  data:
    couchbase:
      auto-index: true

music_host:
  admin:
    username: admin
    password: password
  guest:
    username: guest
    password: password
  storage:
    path: D:\DEVELOP\music_host

jwt:
  secret: youlittlehuckersucker
  age: 2592000 # in seconds, 30 days
