spring:
  couchbase:
    bootstrap-hosts: 192.168.99.100
    bucket:
      name: music_host
      password: password
    env:
      timeouts:
        connect: 10000ms

music_host:
  username: admin
  password: password

jwt:
  secret: youlittlehuckersucker
  age: 2592000 # in seconds, 30 days
